### get products

GET http://localhost:3000/api/products?page=1&limit=10

### get user products

GET http://localhost:3000/api/products/user-products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwic3ViIjoxLCJyb2xlcyI6WyJhZG1pbiIsInVzZXIiXSwiaWF0IjoxNzIyNjk0NjQwLCJleHAiOjE3MjI3ODEwNDB9.KB7_TFtZ6JKHsWaGwx4v51qtb_yTE6R26vbf8rypM0E


### create product

POST http://localhost:3000/api/products/product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwic3ViIjoxLCJyb2xlcyI6WyJhZG1pbiIsInVzZXIiXSwiaWF0IjoxNzIyNjk1ODAwLCJleHAiOjE3MjI3ODIyMDB9.ikMuqPZ_svEG5Ct9zLRBuOIWxbE3yHikVWBVMtfTcBk
Content-Type: application/json

{
    "title":"test24 product",
    "price":1500,
    "count": 4
}