### get user by id

GET http://localhost:3000/api/users/user/6


### get user by email
 
GET http://localhost:3000/api/users/user
Content-Type: application/json

{
    "email":"armin@test.com" 
}


### Find all users and count
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwic3ViIjoxMSwicm9sZXMiOlsiYWRtaW4iLCJ1c2VyIl0sImlhdCI6MTcxNzU4NjMxMiwiZXhwIjoxNzE3NjcyNzEyfQ.ZwIdgzklXe7Whek9eMpz7B6mNqjuQ88T0HdIAtuWFi8


### Delete user by id

DELETE  http://localhost:3000/api/users/user/8


### Update user by id

PATCH  http://localhost:3000/api/users/user/9
Content-Type: application/json

{
    "password":"123456"
}

